version: '3.7'
services:
  mssql:
    #image: microsoft/mssql-server-linux:2017-latest
    image: mcr.microsoft.com/mssql/server:2017-latest
    #image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    ports: ['1433:1433']
    environment:
      - MSSQL_PID=Developer
      - SA_PASSWORD=bbk4k77JKH88g54
      - ACCEPT_EULA=Y

  # You'll need to have a login for https://container-registry.oracle.com and have
  # accepted their terms & conditions. Then prior to running 'docker-compose up -d' you
  # will need to run 'docker login container-registry.oracle.com' to pull the Oracle Database image.
  # Also, Oracle takes considerably more resources.
  # oracle:
  #   image: container-registry.oracle.com/database/standard:12.1.0.2
  #   ports:
  #     - 1521:1521
  #     - 8080:8080
  #     - 5500:5500
  #   environment:
  #     - DB_SID=travis
  #     - DB_PASSWD=bbk4k77JKH88g54
  #     - USERNAME=travis
  #     - PASSWORD=bbk4k77JKH88g54

  ## IBM Db2 is currently on Docker Hub but moving to ICR
  ## After container start please give a little time for the db to be ready for incoming connections
  ## Note that in the connection string for Db2 you need to specify a value for Authentication, eg; 'Authentication=SERVER;'
  db2:
    image: ibmcom/db2:11.5.8.0
    ## Moving forward IBM will publish images to IBM Cloud Registry (which requires an IBM account)
    ## image: icr.io/db2_community/db2
    privileged: true
    restart: always
    ports: ['50000:50000']
    environment:
      - LICENSE=accept
      - DB2INSTANCE=db2inst1 # (default: db2inst1) (this will be username)
      - DB2INST1_PASSWORD=bbk4k77JKH88g54
      - DBNAME=odbc_tst # optional
      # - ENABLE_ORACLE_COMPATIBILITY=true
      - PERSISTENT_HOME=false
      - ARCHIVE_LOGS=false # (default: true) disabling archive logs reduces start up time
      - AUTOCONFIG=false # (default: true) disabling auto configuration on the instance and database reduces start up time
