name: CI

on:
  schedule:
    - cron: '15 3 1 * *'
  push:
  pull_request:
    branches: [ master ]

jobs:
  # Make sure the latest versions of dub and ldc work on all platforms
  build-latest:
    name: ${{ matrix.compiler }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        compiler:
          - dmd-latest
          - ldc-latest
          - dmd-2.096.1
          - dmd-2.095.1
          - dmd-2.094.2
          - dmd-2.093.1
          - dmd-2.092.1
          - dmd-2.091.1
          - dmd-2.090.1
          - dmd-2.089.1
          - dmd-2.088.1
          - dmd-2.087.1
          - dmd-2.086.1
          - dmd-2.085.1
          - dmd-2.077.1
          - dmd-2.076.1 # gdc (gcc v9 - v11.1) supports D at this version
          - ldc-1.25.1 # eq to dmd v2.095.1
          - ldc-1.24.0 # eq to dmd v2.094.1
          - ldc-1.23.0 # eq to dmd v2.093.1
#          - ldc-1.22.0 # eq to dmd v2.092.1
#          - ldc-1.21.0 # eq to dmd v2.091.1
#          - ldc-1.20.1 # eq to dmd v2.090.1
#          - ldc-1.19.0 # eq to dmd v2.089.1
#          - ldc-1.18.0 # eq to dmd v2.088.1
#          - ldc-1.17.0 # eq to dmd v2.087
#          - ldc-1.16.0 # eq to dmd v2.086.1
          - ldc-1.15.0 # eq to dmd v2.085.1
    steps:
      - uses: actions/checkout@v2

      - name: Install D ${{ matrix.compiler }}
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.compiler }}

      - name: Dub Build
        env:
          DC: gdc
        run: dub build --build=release

      - name: Dub Test
        env:
          DC: gdc
        run: dub test

  # On Ubuntu we can use GDC (so keep working for D version 2.076)
  gdc-latest:
    name: GDC on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install DMD (so dub is available)
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-latest

      - name: Install GDC
        run: |
          sudo apt-get update
          sudo apt-get install gdc -y
          gdc --version

      - name: Dub Build
        env:
          DC: gdc
        run: dub build --compiler=gdc --build=release

      - name: Dub Test
        env:
          DC: gdc
        run: dub test --compiler=gdc